# Generated by Django 4.2.4 on 2024-02-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('birth_date', models.DateField()),
                ('department', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('added_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
