# Generated by Django 5.0.4 on 2024-04-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_employee_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
