# Generated by Django 5.0.4 on 2024-05-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_time_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_track',
            name='employee',
            field=models.CharField(max_length=100),
        ),
    ]
