# Generated by Django 5.0.4 on 2024-05-01 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_time_track_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='time_track',
            new_name='Timetrack',
        ),
    ]
