# Generated by Django 5.0.4 on 2024-05-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_time_track_timetrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetrack',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
